### ISSUE TITLE
zone overlay fanlevel error

### ISSUE THREAD

**Issue by aaapee68** [mattdavis90/node-red-contrib-tado-client#63]
I updated tado client from 0.9.* to version 0.10.10 and after that  
Set zone overlay gives an error if the setting ac mode is heat,cool or fan.
"Cannot read properties of undefined (reading 'fanLevel')"
if the setting ac-mode is auto or dry mode everything works ok.
zone state status is:
setting: object
type: "AIR_CONDITIONING"
power: "ON"
mode: "HEAT"
temperature: object
fanSpeed: "LOW"
overlayType: "MANUAL"

**Comment by mattdavis90** [comment]
Hi,

Sorry it has taken a couple of days to reply. I have made quite a few changes changes in the way the air conditioning overlays are handled in the underlying library but don't actually own an AC. Apologies that we didn't notice this before.

I think the issue is likely this line
https://github.com/mattdavis90/node-tado-client/blob/master/src/index.ts#L581

Would you be able to send through the result of a getZoneCapabilities call for the affected zone, I'm guessing there isn't a `FAN` section in the response. If that's the case then we'll need to work out how to determine `fanSpeed` vs. `fanLevel` and alternate way.

Thanks

**Comment by aaapee68** [comment]
Hi

getZoneCapabilities : msg.payload : Object


object


type: "AIR_CONDITIONING"


AUTO: object


fanSpeeds: array[4]


0: "AUTO"


1: "HIGH"


2: "MIDDLE"


3: "LOW"


COOL: object


temperatures: object


celsius: object


fahrenheit: object


fanSpeeds: array[4]


0: "AUTO"


1: "HIGH"


2: "MIDDLE"


3: "LOW"


DRY: object


empty


HEAT: object


temperatures: object


celsius: object


min: 17


max: 30


step: 1


fahrenheit: object


fanSpeeds: array[4]


0: "AUTO"


1: "HIGH"


2: "MIDDLE"


3: "LOW"


initialStates: object


mode: "COOL"


modes: object


AUTO: object


fanSpeed: "LOW"


COOL: object


temperature: object


celsius: 24


fahrenheit: 75


fanSpeed: "LOW"


DRY: object


empty


HEAT: object


temperature: object


celsius: 24


fahrenheit: 75


fanSpeed: "LOW"



17. helmik. 2024 klo 14.01 - lähettäjä ***@***.***:

**Comment by mattdavis90** [comment]
Hi, I've pushed a release of the underlying library along with a new nodered package. Could you test v0.10.11 please? Thanks

**Comment by aaapee68** [comment]
Thanks, a quick test and everything works fine.

17. helmik. 2024 klo 18.24 - lähettäjä ***@***.***:
